# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - footnotes
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
highlighter: pygments
gems:
  - jemoji
# Site settings
title: "Matt Allan's Blog"
description: ""
email: ""
#blog logo
logo: "/assets/images/geodesic_sphere.png"
# blog cover
cover: "/assets/images/IMG_4518.JPG"

name: "Matt Allan"
author: "Matt Allan"
author_image: "https://avatars0.githubusercontent.com/u/9440455?v=3&s=460"

paginate:	5

# url: "http://matthew-james.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@matthew-james-a'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/matthew_james_a
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/matthew-james
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
