# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
gems: [jekyll-paginate]
# Site settings
title: "Matt Allan's Blog"
description: ""
email: ""
#blog logo
logo: "/assets/images/geodesic_sphere.png"
# blog cover
cover: "/assets/images/IMG_4518.JPG"

name: "Matt Allan"
author: "Matt Allan"
author_image: "https://avatars0.githubusercontent.com/u/9440455?v=3&s=460"

paginate:	5

# url: "http://yuloh.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@__yuloh'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/__yuloh
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/yuloh
    desc:	My code on github
    share_url:
    share_title:
    share_link:
